package com.cursos.client.escola.grandecurricular.handler;

import com.cursos.client.escola.grandecurricular.exception.CourseException;
import com.cursos.client.escola.grandecurricular.model.Response;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

import java.util.HashMap;
import java.util.Map;

@ControllerAdvice
public class ResourceHandler {


    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<Response<Map<String, String>>> handleMethodArgumentNotValidException(MethodArgumentNotValidException methodArgumentNotValidException) {

        /**
         * Creating a Map<String, String>
         * and after that, we will mapping all errors for inside of the Map
         */
        Map<String, String> errorsMap = new HashMap<>();

        /**
         * mapping all errors for inside of the errorsMap
         */
        methodArgumentNotValidException
                .getBindingResult()
                .getAllErrors()
                .forEach(objectError -> {

                    String field = ((FieldError) objectError).getField();
                    String value = objectError.getDefaultMessage();

                    errorsMap.put(field, value);
                });

        Response<Map<String, String>> response = new Response();

        response.setData(errorsMap);
        response.setStatusCode(HttpStatus.BAD_REQUEST.value());

        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(response);
    }

    @ExceptionHandler(CourseException.class)
    public ResponseEntity<Response<String>> handleCourseException(CourseException courseException) {
        /**
         * this method ErrorResponse.build() was generated by @Build in model/ErrorResponse.java
         */
        Response<String> response = new Response();

        response.setStatusCode(courseException.getHttpStatus().value());
        response.setData(courseException.getLocalizedMessage());


        return ResponseEntity.status(courseException.getHttpStatus()).body(response);
    }
}
