package com.cursos.client.escola.grandecurricular.handler;

import com.cursos.client.escola.grandecurricular.exception.CourseException;
import com.cursos.client.escola.grandecurricular.model.ErrorResponse;
import com.cursos.client.escola.grandecurricular.model.ErrorResponse.ErrorResponseBuilder;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

@ControllerAdvice
public class ResourceHandler {

    @ExceptionHandler(CourseException.class)
    public ResponseEntity<ErrorResponse> handleCourseException(CourseException courseException) {
        /**
         * this method ErrorResponse.build() was generated by @Build in model/ErrorResponse.java
         */
        ErrorResponseBuilder error = ErrorResponse.builder();

        error.timeStamp(System.currentTimeMillis());
        error.message(courseException.getLocalizedMessage());
        error.httpStatus(courseException.getHttpStatus().value());

        return ResponseEntity.status(courseException.getHttpStatus()).body(error.build());
    }
}
